# Generated by Django 2.0.2 on 2018-03-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Account type'),
        ),
    ]
