# Generated by Django 2.0.2 on 2018-03-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('journalist', 'journalist'), ('redactor', 'redactor'), ('default', 'default')], default='default', max_length=11, null=True, verbose_name='Account type'),
        ),
    ]
